# Generated by Django 3.0.8 on 2020-08-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('yesVotes', models.IntegerField(default=0)),
                ('noVotes', models.IntegerField(default=0)),
                ('yesPercent', models.FloatField(default=0.0)),
                ('noPercent', models.FloatField(default=0.0)),
                ('choiceOne', models.CharField(max_length=50)),
                ('choiceTwo', models.CharField(max_length=50)),
                ('willExpireOn', models.DateTimeField()),
                ('isExpired', models.BooleanField(default=False)),
            ],
        ),
    ]
